# Generated by Django 4.1.5 on 2024-09-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
