# Generated by Django 4.1.5 on 2024-09-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_detail_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='forex',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
