# Generated by Django 4.1.5 on 2024-10-01 17:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_detail_forex_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='forex',
            name='file_type',
            field=models.CharField(choices=[('book', 'book'), ('video', 'video')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
